name: SDR# UDPSignalExporter

on: [push]

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        dotnet-version: [ '7.0.x' ]
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Upload Artifact 
        uses: actions/upload-artifact@v3
        with:
          name: sdrsharp-udp-signal-exporter-${{ github.ref_name}}-${{ github.sha }}
          path: D:\a\sdrsharp-udp-signal-exporter\sdrsharp-udp-signal-exporter\Release\net7.0-windows\

  release:
    runs-on: windows-latest
    if: startsWith( github.ref, 'refs/tags/v')
    strategy:
      matrix:
        dotnet-version: [ '7.0.x' ]
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Archive Release
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          filename: 'sdrsharp-udp-signal-exporter-${{ github.ref_name }}.zip'
          path: D:\a\sdrsharp-udp-signal-exporter\sdrsharp-udp-signal-exporter\Release\net7.0-windows\SDRSharp.UDPSignalExporter.dll
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "${{ github.workspace }}/sdrsharp-udp-signal-exporter-${{ github.ref_name }}.zip"
          draft: true
          name: sdrsharp-udp-signal-exporter ${{ github.ref_name }}